# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='edition',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='title', chained_model_field='title', on_delete=django.db.models.deletion.CASCADE, to='census.Edition'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='issue',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='edition', chained_model_field='edition', on_delete=django.db.models.deletion.CASCADE, to='census.Issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='edition',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='title', chained_model_field='title', on_delete=django.db.models.deletion.CASCADE, to='census.Edition'),
        ),
    ]
