# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyHistory',
            fields=[
                ('copy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.Copy')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('stored_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_history', to='census.Copy')),
            ],
            bases=('census.copy',),
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='edited_copies',
        ),
    ]
