# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={'verbose_name_plural': 'copies'},
        ),
        migrations.AddField(
            model_name='edition',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
