# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20170619_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('data_transaction', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.Copy')),
            ],
        ),
    ]
