# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20171026_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCopy',
            fields=[
                ('copy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.Copy')),
            ],
            bases=('census.copy',),
        ),
        migrations.RemoveField(
            model_name='copy',
            name='parent',
        ),
        migrations.AddField(
            model_name='childcopy',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='census.Copy'),
        ),
    ]
