# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20171031_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcopy',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='census.Copy'),
        ),
    ]
