# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='owner',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='data_transaction',
        ),
    ]
