# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20171031_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcopy',
            name='false_positive_draft',
            field=models.NullBooleanField(default=None),
        ),
    ]
