# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20170710_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='Edition_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
