# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_childcopy_false_positive_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcopy',
            name='false_positive_draft',
        ),
        migrations.AddField(
            model_name='copy',
            name='false_positive_draft',
            field=models.NullBooleanField(default=None),
        ),
    ]
