# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20171027_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcopy',
            name='is_submission',
            field=models.BooleanField(default=False),
        ),
    ]
