# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_auto_20170710_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='Edition_format',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
