# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_auto_20170622_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
    ]
