# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_childcopy_is_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='copy',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
