# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_auto_20171114_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyhistory',
            name='stored_copy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_history', to='census.Copy'),
        ),
    ]
