# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20171027_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcopy',
            name='is_submission',
        ),
    ]
