# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20171114_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='copynote',
        ),
        migrations.AlterField(
            model_name='copy',
            name='Library_Notes',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
