# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20170710_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='year',
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
