# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20170622_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='census.Title'),
        ),
    ]
