# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_auto_20170710_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='notes',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='issue',
            name='ESTC',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='STC_Wing',
            field=models.CharField(max_length=20),
        ),
    ]
