# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_remove_childcopy_is_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='copy',
            name='from_estc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='copy',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
