# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_auto_20171030_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='held_by_library',
            field=models.BooleanField(default=False),
        ),
    ]
