# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_auto_20170627_1325'),
        ('census', '0007_note'),
    ]

    operations = [
    ]
