# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0009_merge_20170703_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AlterField(
            model_name='copy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
