# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0009_copy_held_by_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='false_positive',
            field=models.NullBooleanField(default=None),
        ),
    ]
