# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_auto_20170710_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='Shelfmark',
            field=models.CharField(max_length=100),
        ),
    ]
