# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0011_auto_20170710_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='prov_info',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
