# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_auto_20170705_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to=settings.AUTH_USER_MODEL),
        ),
    ]
