# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_auto_20170710_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='prov_info',
        ),
    ]
