# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_auto_20170710_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='thumbnail_URL',
            field=models.URLField(max_length=500),
        ),
    ]
