# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_userhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='copie',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='copies',
            field=models.ManyToManyField(blank=True, null=True, to='census.Copy'),
        ),
    ]
