# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0016_auto_20170705_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'verbose_name_plural': 'user histories'},
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='copies',
            new_name='editted_copies',
        ),
    ]
