# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0016_auto_20170711_0004'),
        ('census', '0017_auto_20170711_1349'),
    ]

    operations = [
    ]
