# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0018_auto_20170705_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_copies', to=settings.AUTH_USER_MODEL),
        ),
    ]
