# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0019_auto_20170718_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='Barlet1916',
            new_name='Bartlett1916',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Barlet1916_Notes',
            new_name='Bartlett1916_Notes',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Barlett1939',
            new_name='Bartlett1939',
        ),
        migrations.RenameField(
            model_name='copy',
            old_name='Barlet1939_Notes',
            new_name='Bartlett1939_Notes',
        ),
    ]
