# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0020_auto_20170721_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='editted_copies',
            new_name='edited_copies',
        ),
    ]
