# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0021_auto_20170721_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='Bartlett1916_Notes',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Bartlett1939_Notes',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Binder',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Binding',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Bookplate',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Bookplate_Location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Condition',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Lee_Notes',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Library_Notes',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Shelfmark',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='copynote',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
