# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0022_auto_20170724_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='DEEP',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
