# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0023_auto_20170726_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='Height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='NSC',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Width',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='thumbnail_URL',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='Edition_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='Variant_Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='notes',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
