# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0025_auto_20170728_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='Verification',
            field=models.BooleanField(default=False),
        ),
    ]
